platform :ios, '12.0'

# CocoaPods analytics sends network stats. Uncomment to disable.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# If you have a custom setup, adjust the use_frameworks!/use_modular_headers! lines.
# Flutter will typically add the correct Pod configuration when you run `pod install` on macOS.

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Install all pods required by Flutter plugins.
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
